# Generated by Django 5.2.6 on 2025-10-17 15:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='status_orcamento',
        ),
        migrations.AddField(
            model_name='orcamento',
            name='categoria',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Black', 'Black'), ('Clássico', 'Clássico'), ('Novo', 'Novo'), ('Special', 'Special')], default='Novo', max_length=20),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='data_envio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='data_previsao_fechamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='data_solicitacao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='especificador',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='etapa',
            field=models.CharField(choices=[('Perdida', 'Perdida'), ('Fechada e Ganha', 'Fechada e Ganha'), ('Em Negociação', 'Em Negociação'), ('Revisão de Projeto', 'Revisão de Projeto'), ('B2B', 'B2B'), ('Especificação', 'Especificação')], default='Especificação', max_length=50),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='jornada_cliente',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='numero_orcamento',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='semana_previsao_fechamento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='termometro',
            field=models.CharField(choices=[('Quente', 'Quente'), ('Morno', 'Morno'), ('Frio', 'Frio')], default='Frio', max_length=6),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='nome_cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='valor_orcamento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
