# Generated by Django 5.2.6 on 2025-10-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cliente_especificador_alter_orcamento_nome_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='data_fechada_ganha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
