# Generated by Django 5.2.6 on 2025-10-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_jornadaclientehistorico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornadaclientehistorico',
            name='data_edicao',
            field=models.DateTimeField(),
        ),
    ]
