# Generated by Django 5.2.6 on 2025-11-03 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_loja_to_loja_old'),
    ]

    operations = [

        migrations.AddField(
            model_name='user',
            name='loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.loja'),
        ),
    ]
