# Generated by Django 5.2.6 on 2025-11-03 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_populate_user_loja_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='loja_old',
        ),
    ]
