# Generated by Django 5.2.6 on 2025-11-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_user_loja_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornadaclientehistorico',
            name='data_edicao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
