# Generated by Django 5.2.6 on 2025-11-17 14:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribed_orcamentos', to=settings.AUTH_USER_MODEL),
        ),
    ]
