# Generated by Django 5.2.6 on 2025-11-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_orcamento_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='is_forecast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='motivo_perda',
            field=models.CharField(blank=True, choices=[('Preço', 'Preço'), ('Concorrência', 'Concorrência'), ('Prazo', 'Prazo'), ('Qualidade', 'Qualidade'), ('Cliente Indeciso', 'Cliente Indeciso'), ('Outros', 'Outros')], max_length=50, null=True),
        ),
    ]
