# Generated by Django 5.2.6 on 2025-11-25 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_orcamento_is_forecast_orcamento_motivo_perda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('consultor', 'Consultor'), ('gerente', 'Gerente'), ('administrador', 'Administrador'), ('facilitis', 'Facilitis')], max_length=20),
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala', models.CharField(choices=[('Esperienza 1', 'Esperienza 1'), ('Esperienza 2', 'Esperienza 2'), ('Laccato', 'Laccato'), ('Lacca', 'Lacca'), ('Loja Artefacto', 'Loja Artefacto'), ('Apresentação da Loja', 'Apresentação da Loja'), ('Obra', 'Obra'), ('Recepção', 'Recepção'), ('Acolhida', 'Acolhida'), ('Espaço Café IJP', 'Espaço Café IJP'), ('Espaço Brayan', 'Espaço Brayan'), ('Ambiente Shame', 'Ambiente Shame'), ('Sala Cultura', 'Sala Cultura'), ('Espaço Malu', 'Espaço Malu'), ('Portobello Showroom', 'Portobello Showroom')], max_length=50)),
                ('horario_inicio', models.DateTimeField()),
                ('horario_fim', models.DateTimeField()),
                ('quantidade_convidados', models.PositiveIntegerField(default=1)),
                ('conveniencia', models.BooleanField(default=False)),
                ('motivo', models.CharField(choices=[('Reunião de Negócios', 'Reunião de Negócios'), ('Apresentação de Produto', 'Apresentação de Produto'), ('Treinamento', 'Treinamento'), ('Entrevista', 'Entrevista'), ('Evento Corporativo', 'Evento Corporativo'), ('Visita Técnica', 'Visita Técnica'), ('Brainstorming', 'Brainstorming'), ('Workshop', 'Workshop'), ('Demonstração', 'Demonstração'), ('Outros', 'Outros')], max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cliente')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos_criados', to=settings.AUTH_USER_MODEL)),
                ('especificador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.especificador')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='core.loja')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos_responsaveis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['horario_inicio'],
            },
        ),
    ]
