# Generated by Django 5.2.6 on 2025-11-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_user_role_agendamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='sala',
            field=models.CharField(choices=[('Esperienza 1', 'Esperienza 1'), ('Esperienza 2', 'Esperienza 2'), ('Laccato', 'Laccato'), ('Lacca', 'Lacca'), ('Loja Artefacto', 'Loja Artefacto'), ('Recepção Bontempo', 'Recepção Bontempo'), ('Acolhida', 'Acolhida'), ('Espaço Café IJP', 'Espaço Café IJP'), ('Espaço Brayan', 'Espaço Brayan'), ('Ambiente Sihame', 'Ambiente Sihame'), ('Sala Cultura', 'Sala Cultura'), ('Espaço Malu & Nathasha', 'Espaço Malu & Nathasha'), ('Portobello Shop', 'Portobello Shop'), ('Espaço da Mylena', 'Espaço da Mylena'), ('Espaço Maria Helena', 'Espaço Maria Helena'), ('Espaço Lediane', 'Espaço Lediane'), ('Estacionamento', 'Estacionamento'), ('Atendimento Artefacto', 'Atendimento Artefacto'), ('Espaço Theka e Renata', 'Espaço Theka e Renata'), ('Sala CEO Igor', 'Sala CEO Igor'), ('Sala CEO João', 'Sala CEO João'), ('Sala Head Comercial', 'Sala Head Comercial'), ('Office', 'Office'), ('Sala Gerência Bontempo', 'Sala Gerência Bontempo')], max_length=50),
        ),
    ]
