# Generated by Django 5.2.6 on 2025-11-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_agendamento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='conveniencia_detalhes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='motivo',
            field=models.CharField(choices=[('Especificação', 'Especificação'), ('Apresentação Showroom', 'Apresentação Showroom'), ('Apresentação Produtos', 'Apresentação Produtos'), ('Apresentação Orçamentos', 'Apresentação Orçamentos'), ('Pagamento', 'Pagamento'), ('Gravação', 'Gravação'), ('Negociação e Fechamento', 'Negociação e Fechamento'), ('Revisão de Projeto', 'Revisão de Projeto'), ('Relacionamento', 'Relacionamento')], max_length=50),
        ),
    ]
