# Generated by Django 5.2.6 on 2025-11-26 18:38

from django.db import migrations

def add_lojas(apps, schema_editor):
    Loja = apps.get_model('core', 'Loja')
    Loja.objects.get_or_create(nome='RH')
    Loja.objects.get_or_create(nome='Diretoria')

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_agendamento_conveniencia_detalhes_and_more'),
    ]

    operations = [
        migrations.RunPython(add_lojas),
    ]
