# Generated by Django 5.2.6 on 2025-11-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_add_rh_diretoria_lojas'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='conveniencia_status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('entregue', 'Entregue')], default='pendente', max_length=20),
        ),
    ]
