# Generated by Django 5.2.6 on 2025-11-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_agendamento_conveniencia_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='sala',
            field=models.CharField(choices=[('Esperienza 1', 'Esperienza 1'), ('Esperienza 2', 'Esperienza 2'), ('Laccato', 'Laccato'), ('Lacca', 'Lacca'), ('Portobello Shop', 'Portobello Shop'), ('Recepção Artefacto', 'Recepção Artefacto'), ('Café IJP', 'Café IJP'), ('Office Artefacto', 'Office Artefacto'), ('Jantar Formal - Artefacto', 'Jantar Formal - Artefacto'), ('Sala de Reunião Smart', 'Sala de Reunião Smart'), ('Espaço Hunter Douglas', 'Espaço Hunter Douglas'), ('Sala Cultura', 'Sala Cultura')], max_length=50),
        ),
    ]
