# Generated by Django 5.2.6 on 2025-11-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_agendamento_sala'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='conveniencia_detalhes',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='conveniencia_pedido',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
