# Generated by Django 5.2.6 on 2025-11-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_agendamento_conveniencia_detalhes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='sala_limpa',
            field=models.BooleanField(default=False),
        ),
    ]
