from django.urls import path
from .views import (
    home_view, LojasView, register_user_view, logout_view,
    UserListView, user_edit_view, user_deactivate_view, user_activate_view, consultor_dashboard, consultor_criar_orcamento,
    add_cliente, add_especificador, edit_orcamento, gerente_dashboard,
    gerente_criar_orcamento, meus_clientes_view, todos_orcamentos_view,
    marcar_como_ganho, consultor_orcamentos_fechados_ganhos,
    reverter_orcamento_ganho, administrador_dashboard, administrador_criar_orcamento, add_jornada_cliente_comment,
    add_cliente_full, clientes_cadastrados, cliente_add_view, cliente_edit_view, importar_orcamentos, orcamentos_fechados_view,
    download_template_view, search_clientes, search_especificadores, notifications_view,
    especificadores_cadastrados, especificador_add_view, especificador_edit_view,
    gerente_forecast_view, admin_forecast_dashboard_view, get_orcamento_details, update_orcamento_details,
    update_forecast_status
)

urlpatterns = [
    path('notifications/', notifications_view, name='notifications'),
    path('register/', register_user_view, name='register'),
    path('home/', home_view, name='home'),
    path('lojas/', LojasView.as_view(), name='lojas'),
    path('logout/', logout_view, name='logout'),
    path('users/', UserListView.as_view(), name='user_list'),
    path('users/<int:pk>/edit/', user_edit_view, name='user_edit'),
    path('users/<int:pk>/deactivate/', user_deactivate_view, name='user_deactivate'),
    path('users/<int:pk>/activate/', user_activate_view, name='user_activate'),
    path('dashboard/', consultor_dashboard, name='consultor_dashboard'),
    path('consultor/criar-orcamento/', consultor_criar_orcamento, name='consultor_criar_orcamento'),
    path('administrador/dashboard/', administrador_dashboard, name='administrador_dashboard'),
    path('administrador/forecast-dashboard/', admin_forecast_dashboard_view, name='admin_forecast_dashboard'),
    path('administrador/criar-orcamento/', administrador_criar_orcamento, name='administrador_criar_orcamento'),
    path('administrador/importar-orcamentos/', importar_orcamentos, name='importar_orcamentos'),
    path('administrador/importar-orcamentos/download-template/', download_template_view, name='download_template'),
    path('gerente/dashboard/', gerente_dashboard, name='gerente_dashboard'),
    path('gerente/criar-orcamento/', gerente_criar_orcamento, name='gerente_criar_orcamento'),
    path('gerente/forecast/', gerente_forecast_view, name='gerente_forecast'),
    path('gerente/forecast/update/', update_forecast_status, name='update_forecast_status'),
    path('gerente/meus-clientes/', meus_clientes_view, name='meus_clientes_gerente'),
    path('consultor/meus-clientes/', meus_clientes_view, name='meus_clientes_consultor'),
    path('administrador/meus-clientes/', meus_clientes_view, name='meus_clientes_administrador'),
    path('gerente/todos-orcamentos/', todos_orcamentos_view, name='todos_orcamentos_gerente'),
    path('administrador/todos-orcamentos/', todos_orcamentos_view, name='todos_orcamentos_administrador'),
    path('orcamento/<int:pk>/marcar_como_ganho/', marcar_como_ganho, name='marcar_como_ganho'),
    path('consultor/orcamentos-fechados-ganhos/', consultor_orcamentos_fechados_ganhos, name='consultor_orcamentos_fechados_ganhos'),
    path('orcamento/<int:pk>/reverter/', reverter_orcamento_ganho, name='reverter_orcamento_ganho'),
    path('add_cliente/', add_cliente, name='add_cliente'),
    path('add_cliente_full/', add_cliente_full, name='add_cliente_full'), # New URL pattern
    path('add_especificador/', add_especificador, name='add_especificador'),
    path('search-clientes/', search_clientes, name='search_clientes'),
    path('search-especificadores/', search_especificadores, name='search_especificadores'),
    path('orcamento/<int:pk>/edit/', edit_orcamento, name='edit_orcamento'),
    path('orcamento/<int:pk>/add-jornada-comment/', add_jornada_cliente_comment, name='add_jornada_cliente_comment'),
    path('clientes_cadastrados/', clientes_cadastrados, name='clientes_cadastrados'),
    path('cliente/add/', cliente_add_view, name='cliente_add'),
    path('cliente/<int:pk>/edit/', cliente_edit_view, name='cliente_edit'),
    path('especificadores_cadastrados/', especificadores_cadastrados, name='especificadores_cadastrados'),
    path('especificador/add/', especificador_add_view, name='especificador_add'),
    path('especificador/<int:pk>/edit/', especificador_edit_view, name='especificador_edit'),
    path('orcamentos-fechados/', orcamentos_fechados_view, name='orcamentos_fechados'),
    
    # API URLs for modal
    path('api/orcamento/<int:pk>/details/', get_orcamento_details, name='get_orcamento_details'),
    path('api/orcamento/<int:pk>/update/', update_orcamento_details, name='update_orcamento_details'),
]

